/**
 * \file main.h
 * Public interface of the main emulator module (main.c).
 */

// Public interface to the emulator

#pragma once

#ifdef __cplusplus
extern "C" {
#endif

// ST: Communication with main emulator (main.c)
/** Reads the command line, sets up paths and loads the default settings. */
void  main_startup(void);
/** Runs the main emulator thread: opens the console view, boots the ROM, runs startup commands and enters the debug UI loop. */
void  main_thread(void);

// works like printf for executing commands, returns all the text this
// command generates (up to 4K). Scan it for errors if you want.
//
// NOTE: If emulator is executing when command is given, main_stop is
// automatically called, and main_start executed after the command. If you
// want to do multiple commands while executing, it's better to first
// call main_stop manually, then the commands, and then restart.
/**
 * Executes a command as if typed in the console and returns all printed text.
 * @param cmd Command format string.
 * @return The text generated by the command (up to 1K), or an exception message if execution could not be stopped.
 */
char *main_command(char *cmd,...);

// this returns the same text returned by last main_commmand
/**
 * Returns the text produced by the last main_command call.
 * @return The accumulated command output text.
 */
char *main_commandreturn(void);
// this returns severity of errors from last main_command:
// 0=no errors, 1=warnings only, 2=errors, 3=exceptions
/**
 * Returns the error severity of the last main_command call.
 * @return Error severity: 0=none, 1=warnings, 2=errors, 3=exceptions.
 */
int   main_commanderrors(void);

// emulation go/stop (DO NOT USE command("go"))
/**
 * Stops emulation, escalating from a nice break to a forced CPU break if needed.
 * @return 0 on success, 1 if the emulator could not be stopped.
 */
int   main_stop(void); // returns 1 if unable to stop (emulator crashed)
/**
 * Starts emulation and waits until it is actually running.
 * @return 0 on success, 1 if execution did not start.
 */
int   main_start(void);
/**
 * Checks whether emulation is currently executing.
 * @return 1 if execution is in progress, 0 otherwise.
 */
int   main_executing(void); // returns 1 if execution in progress

// deinitializes 3dfx. It is automatically reinitialized when executing
// and the rom generates a new frame. Execution no longer needs to be
// stopped when calling these.
/** Hides the 3dfx display; it is reinitialized automatically on the next frame, resuming execution if it was running. */
void  main_hide3dfx(void);
/** Shows the 3dfx display again, resuming execution if it was running. */
void  main_show3dfx(void);

/**
 * Returns the handle of the main application window, used for DirectSound init.
 * @return The main window handle.
 */
void* main_gethwnd(void);

/**
 * Hook receiving console output lines for further processing: tracks errors and warnings and buffers the text returned by main_command.
 * @param txt Text with the common color codes at the start stripped.
 * @param full Full line including the color codes.
 */
void outputhook(char* txt, char* full);

/**
 * Appends a trailing backslash to the given path.
 * @param path Path string to fix.
 * @param striplastname If non-zero, removes the last path component first.
 */
void fixpath(char* path, int striplastname);

/** Prints the application name, version and copyright lines to the console. */
void printcopyright(void);

/** When non-zero, the 'go' and 'sgo' console commands are ignored. */
extern int godisabled;

#ifdef __cplusplus
};
#endif
